# Generated by Django 4.2.7 on 2026-08-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('language_level', models.CharField(choices=[('zero', 'С нуля'), ('beginner', 'Начальный'), ('elementary', 'Элементарный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='zero', max_length=20, verbose_name='Уровень языка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('enrolled', 'Зачислен'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
    ]
