# Generated by Django 5.0.14 on 2026-08-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('courses', '0001_initial'),
        ('lms', '0003_group_capacity_activitylog_notification'),
        ('teachers', '0002_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки CRM'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('google', 'Google'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referral', 'Рекомендация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник заявки'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Статус изменён'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались'), ('test', 'Записан на тест'), ('test_passed', 'Тест пройден'), ('enrolled', 'Зачислен'), ('rejected', 'Отказался'), ('lost', 'Потерянный лид')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.studentapplication', verbose_name='Заявка')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_history', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Изменение статуса',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Пусто — сгенерируется автоматически', max_length=200, verbose_name='Название набора')),
                ('days', models.CharField(blank=True, help_text='Коды дней через запятую: mon,wed,fri', max_length=100, verbose_name='Дни занятий')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта группы')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Сколько заявок принимаем (пусто — без лимита)', null=True, verbose_name='Максимум мест')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('archived', 'Архив')], default='open', max_length=20, verbose_name='Статус')),
                ('notified_80', models.BooleanField(default=False, verbose_name='Уведомлено о 80%')),
                ('notified_90', models.BooleanField(default=False, verbose_name='Уведомлено о 90%')),
                ('notified_100', models.BooleanField(default=False, verbose_name='Уведомлено о 100%')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sets', to='applications.branch', verbose_name='Филиал')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sets', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sets_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_set', to='lms.group', verbose_name='Созданная группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sets', to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Набор группы',
                'verbose_name_plural': 'Наборы групп',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='group_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.groupset', verbose_name='Набор'),
        ),
        migrations.CreateModel(
            name='SpendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('google', 'Google'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referral', 'Рекомендация'), ('other', 'Другое')], max_length=20, verbose_name='Источник')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма (сом)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Расход на маркетинг',
                'verbose_name_plural': 'Расходы на маркетинг',
                'ordering': ['-month'],
                'unique_together': {('source', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомлён об освобождении места')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('group_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='applications.groupset', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Запись листа ожидания',
                'verbose_name_plural': 'Лист ожидания',
                'ordering': ['-created_at'],
            },
        ),
    ]
