# Generated by Django 5.0.14 on 2026-08-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_branch_studentapplication_created_by_and_more'),
        ('lms', '0003_group_capacity_activitylog_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='lms.studentprofile', verbose_name='Созданный ученик'),
        ),
    ]
