# Generated by Django 5.1.4 on 2026-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_studentapplication_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались'), ('test', 'Записан на тест'), ('test_passed', 'Тест пройден'), ('enrolled', 'Зачислен'), ('rejected', 'Отказался'), ('lost', 'Потерянный лид')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
