# Generated by Django 5.1.4 on 2026-08-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_studentapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupset',
            name='is_night',
            field=models.BooleanField(default=False, help_text='На главной странице отображается в ночном оформлении', verbose_name='Ночная группа'),
        ),
    ]
