# Generated by Django 4.2.7 on 2026-08-05 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('korean', 'Корейский язык'), ('english', 'Английский язык'), ('german', 'Немецкий язык'), ('chinese', 'Китайский язык'), ('tips', 'Советы по обучению'), ('exams', 'Экзамены'), ('study_abroad', 'Учёба за рубежом'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Изображение')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=300, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO: Description')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO: Description')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
