# Generated by Django 4.2.7 on 2026-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения с сайта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('classes', 'Классы'), ('events', 'Мероприятия'), ('students', 'Студенты'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+996 700 995 577', max_length=50, verbose_name='Телефон')),
                ('whatsapp', models.CharField(default='996700995577', max_length=50, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='А. Масалиева 44, ТЦ Корона, 3 этаж, Ош, Кыргызстан', max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/edupoint.ec', verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='Favicon')),
                ('meta_title', models.CharField(default='Edu Point — Языковой центр в Оше', max_length=255, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(default='Изучайте корейский, английский, немецкий и китайский языки в Edu Point. Подготовка к TOPIK, IELTS, GOETHE. Ош, Кыргызстан.', verbose_name='SEO: Description')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
