# Generated by Django 4.2.7 on 2026-08-05 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('topik', 'TOPIK'), ('ielts', 'IELTS'), ('goethe', 'GOETHE')], max_length=10, unique=True, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание экзамена')),
                ('preparation_program', ckeditor.fields.RichTextField(blank=True, verbose_name='Программа подготовки')),
                ('benefits', models.TextField(blank=True, help_text='Каждое с новой строки', verbose_name='Преимущества курса')),
                ('image', models.ImageField(blank=True, upload_to='exams/', verbose_name='Изображение')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Длительность подготовки')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена (сом)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO: Description')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['order'],
            },
        ),
    ]
