# Generated by Django 4.2.7 on 2026-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='Преподаватель', max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Опыт (лет)')),
                ('education', models.CharField(blank=True, max_length=300, verbose_name='Образование')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Преподаёт языки')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['order', 'name'],
            },
        ),
    ]
