# Generated by Django 5.1.4 on 2026-08-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_theme',
            field=models.CharField(blank=True, choices=[('', 'Обычное оформление'), ('korean', '🇰🇷 Корейская тема (ханок, ханбок)')], default='', help_text='Особое оформление публичного профиля и личного кабинета', max_length=20, verbose_name='Оформление профиля'),
        ),
    ]
