# Generated by Django 5.1.4 on 2026-08-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='teachers.teacher', verbose_name='Преподаватель'),
        ),
    ]
