# Generated by Django 4.2.7 on 2026-08-05 16:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('language_code', models.CharField(choices=[('korean', 'Корейский'), ('english', 'Английский'), ('german', 'Немецкий'), ('chinese', 'Китайский')], max_length=20, unique=True, verbose_name='Код языка')),
                ('flag_emoji', models.CharField(default='🌐', max_length=10, verbose_name='Флаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('color', models.CharField(default='#0EA5E9', max_length=7, verbose_name='Цвет (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории языков',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('level', models.CharField(choices=[('beginner', 'Начальный (A1-A2)'), ('elementary', 'Элементарный (A2-B1)'), ('intermediate', 'Средний (B1-B2)'), ('advanced', 'Продвинутый (C1-C2)'), ('all', 'Все уровни')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('duration', models.CharField(default='3 месяца', max_length=100, verbose_name='Длительность')),
                ('lessons_per_week', models.PositiveIntegerField(default=3, verbose_name='Занятий в неделю')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена (сом)')),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO: Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='Язык')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
