# Generated by Django 5.1.4 on 2026-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_group_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон родителя'),
        ),
    ]
