# Generated by Django 5.1.4 on 2026-08-11 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_studentprofile_parent_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month'], name='lms_payment_student_657480_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentextension',
            index=models.Index(fields=['student', 'month'], name='lms_payment_student_f856c0_idx'),
        ),
    ]
