# Generated by Django 5.1.4 on 2026-08-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_payment_lms_payment_student_657480_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='trial_date',
            field=models.DateField(blank=True, help_text='До этой даты и один день после — статус «Пробный урок», не Frozen', null=True, verbose_name='Дата пробного урока'),
        ),
    ]
