# Generated by Django 4.2.7 on 2026-08-05 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название игры')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('icon', models.CharField(default='🎮', max_length=50, verbose_name='Иконка (эмодзи)')),
                ('category', models.CharField(choices=[('vocab', 'Словарный запас'), ('grammar', 'Грамматика'), ('typing', 'Скорость и память'), ('mafia', 'Мафия и логика'), ('exam', 'Экзамены и дуэли')], default='vocab', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание и правила')),
                ('rules_json', models.TextField(default='[]', help_text='Правила игры в формате JSON массива')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_rounds', models.IntegerField(default=10, verbose_name='Число раундов по умолчанию')),
                ('default_time_sec', models.IntegerField(default=20, verbose_name='Секунд на раунд')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Мини-игра',
                'verbose_name_plural': 'Мини-игры',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=1)),
                ('player_name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('score', models.IntegerField(default=0, verbose_name='Очки')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_answers', models.IntegerField(default=0, verbose_name='Всего ответов')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.game')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Номер комнаты (1-4)')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('host_name', models.CharField(default='Ожидает хоста', max_length=100, verbose_name='Имя хоста')),
                ('host_session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сессии хоста')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занята')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий (A1-A2)'), ('medium', 'Средний (B1-B2)'), ('hard', 'Сложный (C1-C2)'), ('mixed', 'Смешанный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('max_rounds', models.IntegerField(default=10, verbose_name='Количество раундов')),
                ('round_time_sec', models.IntegerField(default=20, verbose_name='Время на раунд (сек)')),
                ('target_language', models.CharField(default='all', max_length=20, verbose_name='Язык (корейский, английский, немецкий, китайский, все)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Комната игры',
                'verbose_name_plural': 'Комнаты игр',
                'ordering': ['game', 'room_number'],
                'unique_together': {('game', 'room_number')},
            },
        ),
    ]
