# Generated by Django 4.2.7 on 2026-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='max_players',
            field=models.IntegerField(default=4, verbose_name='Максимум игроков (2-8)'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий (Начинающий A1-A2)'), ('medium', 'Средний (B1-B2)'), ('hard', 'Продвинутый (C1-C2)'), ('mixed', 'Смешанный')], default='easy', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='target_language',
            field=models.CharField(choices=[('all', '🌐 Все языки (Смешанный)'), ('korean', '🇰🇷 Корейский'), ('english', '🇬🇧 Английский'), ('german', '🇩🇪 Немецкий'), ('chinese', '🇨🇳 Китайский')], default='korean', max_length=20, verbose_name='Целевой язык'),
        ),
    ]
