# Generated by Django 4.2.7 on 2026-08-05 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameroom_max_players_alter_gameroom_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании игроков'), ('in_game', 'Идёт игра'), ('finished', 'Завершена / Свободна')], default='waiting', max_length=20, verbose_name='Статус комнаты'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='host_name',
            field=models.CharField(default='Свободна (нажмите стать хостом)', max_length=100, verbose_name='Имя хоста'),
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Имя реального игрока')),
                ('session_key', models.CharField(max_length=100, verbose_name='Session Key')),
                ('is_host', models.BooleanField(default=False, verbose_name='Хост')),
                ('is_ready', models.BooleanField(default=True, verbose_name='Готов')),
                ('avatar', models.CharField(default='😎', max_length=10)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameroom')),
            ],
            options={
                'verbose_name': 'Игрок комнаты',
                'verbose_name_plural': 'Игроки комнат',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'session_key')},
            },
        ),
    ]
