# Generated by Django 4.2.7 on 2026-08-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameroom_status_alter_gameroom_host_name_roomplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['-is_win', '-score', '-created_at'], 'verbose_name': 'Результат игры', 'verbose_name_plural': 'Результаты игр'},
        ),
        migrations.AddField(
            model_name='gameresult',
            name='is_win',
            field=models.BooleanField(default=False, verbose_name='Победа в матче (1-е место)'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Очки за матч'),
        ),
    ]
